#pragma once

#define DISABLE_GAMEPAD_INPUT

#define IMGUI_DEFINE_MATH_OPERATORS

#define IMGUI_USE_STB_SPRINTF


#ifndef NDEBUG
#define SHOW_IMGUI_DEMO
#endif

#ifndef SHOW_IMGUI_DEMO
#define IMGUI_DISABLE_DEMO_WINDOWS
#endif